version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend/app/:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped
    profiles:
      - dev

  frontend-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # default target = prod
    container_name: frontend-prod
    ports:
      - "3000:3000"
    restart: unless-stopped
    profiles:
      - prod

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #     target: dev
  #   container_name: backend
  #   ports:
  #     - "4000:4000"
  #   volumes:
  #     - ./backend:/app
  #     - backend_node_modules:/app/node_modules
  #   restart: unless-stopped
  #   profiles:
  #     - dev
  #
  # backend-prod:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #     # default target = prod
  #   container_name: backend-prod
  #   ports:
  #     - "4000:4000"
  #   restart: unless-stopped
  #   profiles:
  #     - prod
  #
  # db:
  #   build:
  #     context: ./db
  #     dockerfile: Dockerfile
  #   container_name: db
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - db-data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   restart: unless-stopped

volumes:
  db-data:
  frontend_node_modules:
  backend_node_modules:
